project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Haiyang Gao"
  description: "Mathmatical Finance"
  navbar:
    background: "#023a75ff"
    foreground: "#ffffffff"
    left:
      - text: CV
        href: curriculum.qmd
      - text: Study Vault
        href: study vault.qmd
    right:
      - icon: github
        href: https://github.com/Haiyang-Gao/
      - icon: envelope
        href: "highsea_econ@icloud.com"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    linkcolor: black



